#!/bin/bash

# This script cleans up the content generated by gencerts.sh.

# isYes function checks to see if the yesVar variable is "Y" or "YES" ignoring case, and set the yesResult variable appropriately
isYes() {
    if [ "$yesVar" = "y" ]|| [ "$yesVar" = "Y" ] || [ "$yesVar" = "yes" ] || [ "$yesVar" = "Yes" ] || [ "$yesVar" = "YES" ];
    then
        true
    else
        false
    fi
}

# endScript is a function that ends the script in proper fashion
endScript() {
  read -p "End of script, thank you for chosing bash! Press any key to continue..."
  exit
}

if [ -d "./CA" ];
then
    read -p "Would you like to clean up the CA? (Y/N): " yesVar
    if isYes;
    then
        rm -r ./CA
        echo "Cleaned up the CA."
    fi
else
    echo "CA already clean."
fi

if [ -d "./output" ];
then
    read -p "Would you like to clean up the output? (Y/N): " yesVar
    if isYes;
    then
        rm -r ./output
        echo "Cleaned up the output."
    fi
else
    echo "Output already clean."
fi

endScript
